# doc: https://packit.dev/docs/
# config: https://packit.dev/docs/configuration/
---

specfile_path: chkconfig.spec

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all
