# doc: https://packit.dev/docs/
---

specfile_path: ./chkconfig.spec

jobs:
  - &copr
    job: copr_build
    trigger: pull_request
    targets:
      - fedora-rawhide-x86_64

  - <<: *copr
    trigger: release
