.TH CHKCONFIG 8 "Wed Oct 8 1997"
.UC 4
.SH NAME
chkconfig \- updates and queries runlevel information for system services

.SH SYNOPSIS
\fBchkconfig\fR \fB--list\fR [\fIname\fR]
.br
\fBchkconfig\fR \fB--add\fR \fIname\fR
.br
\fBchkconfig\fR \fB--del\fR \fIname\fR
.br
\fBchkconfig\fR [\fB--level\fR \fIlevels\fR] \fIname\fR <\fBon\fR|\fBoff\fR|\fBreset\fR>
.br
\fBchkconfig\fR [\fB--level\fR \fIlevels\fR] \fIname\fR 
.br

.SH DESCRIPTION
\fBchkconfig\fR provides a simple command-line tool for maintaining the
/etc/rc[0-6].d directory hierarchy by relieving system administrators of
the task of directly manipulating the numerous symbolic links in those
directories.

This implementation of \fBchkconfig\fR was inspired by the \fBchkconfig\fR
command present in the IRIX operating system. Rather than maintaining 
configuration information outside of the /etc/rc[0-6].d hierarchy, however,
this version directly manages the symlinks in /etc/rc[0-6].d. This leaves all
of the configuration information regarding what services \fIinit\fR
starts in a single location.

\fBchkconfig\fR has five distinct functions: adding new services for
management, removing services from management, listing the current
startup information for services, changing the startup information
for services, and checking the startup state of a particular service.

When \fBchkconfig\fR is run without any options, it displays usage
information.  If only a service name is given, it checks to see if
the service is configured to be started in the current runlevel. If
it is, \fBchkconfig\fR returns true; otherwise it returns false. The
\fB--level\fR option may be used to have \fBchkconfig\fR query an
alternative runlevel rather than the current one.

If one of \fBon\fR, \fBoff\fR, or \fRreset\fR is specified after the
service name, \fBchkconfig\fR changes the startup information for the
specified service.  The \fBon\fR and \fBoff\fR flags cause the service
to be started or stopped, respectively, in the runlevels being changed.
The \fBreset\fR flag resets the startup information for the service to
whatever is specified in the init script in question.

By default, the \fBon\fR and \fBoff\fR options affect only runlevels 2, 3, 4,
and 5, while \fBreset\fR affects all of the runlevels.  The \fB--level\fR
option may be used to specify which runlevels are affected.

Note that for every service, each runlevel has either a start script
or a stop script.  When switching runlevels, init will not re-start
an already-started service, and will not re-stop a service that is
not running.

\fBchkconfig\fR also can manage xinetd scripts via the means
of xinetd.d configuration files. Note that only the
\fBon\fR, \fBoff\fR, and \fB-\-list\fR commands are supported
for xinetd.d services.

.SH OPTIONS
.TP
\fB-\-level \fIlevels\fR
Specifies the run levels an operation should pertain to. It is given as
a string of numbers from 0 to 6. For example, \fB--level 35\fR specifies
runlevels 3 and 5.

.TP
\fB-\-add\fR \fIname\fR

This option adds a new service for management by \fBchkconfig\fR.
When a new service is added, \fBchkconfig\fR ensures that the service
has either a start or a kill entry in every runlevel. If any runlevel
is missing such an entry, \fBchkconfig\fR creates the appropriate entry
as specified by the default values in the init script. Note that
default entries in LSB-delimited 'INIT INFO' sections take precedence
over the default runlevels in the initscript.

.TP
\fB-\-del\fR \fIname\fR
The service is removed from \fBchkconfig\fR management, and any symbolic
links in /etc/rc[0-6].d which pertain to it are removed.

Note that future package installs for this service may run
\fBchkconfig \-\-add\fR, which will re-add such links. To disable a
service, run \fBchkconfig \fIname\fR \fBoff\fR.

.TP
\fB-\-list\fR \fIname\fR
This option lists all of the services which \fBchkconfig\fR knows about,
and whether they are stopped or started in each runlevel. If \fIname\fR
is specified, information in only display about service \fIname\fR.

.SH RUNLEVEL FILES

Each service which should be manageable by \fBchkconfig\fR needs two
or more commented lines added to its init.d script. The first line
tells \fBchkconfig\fR what runlevels the service should be started in
by default, as well as the start and stop priority levels. If the service
should not, by default, be started in any runlevels, a \fB\-\fR should be
used in place of the runlevels list.  The second
line contains a description for the service, and may be extended across
multiple lines with backslash continuation.

For example, random.init has these three lines:
.nf
.fn C
# chkconfig: 2345 20 80
# description: Saves and restores system entropy pool for \e
#              higher quality random number generation.
.fn R
.fi
This says that the random script should be started in levels 2, 3, 4,
and 5, that its start priority should be 20, and that its stop
priority should be 80.  You should be able to figure out what the
description says; the \e causes the line to be continued.  The
extra space in front of the line is ignored.

.SH SEE ALSO
.IR init (8)
.IR ntsysv (8)
.IR system-config-services (8)

.SH AUTHOR
.nf
Erik Troan <ewt@redhat.com>
.fi
